//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.17 at 08:38:41 odp. CET 
//


package net.javacrumbs.smock.common.server.test;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.javacrumbs.calc.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.javacrumbs.calc.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlusResponse }
     * 
     */
    public PlusResponse createPlusResponse() {
        return new PlusResponse();
    }

    /**
     * Create an instance of {@link PlusRequest }
     * 
     */
    public PlusRequest createPlusRequest() {
        return new PlusRequest();
    }

}
